### ISSUE TITLE
Compiler doesn't work

### ISSUE THREAD

**Issue by Enz0B** [TommyB123/eSelection#6]
When i define the include eSelection, and i put PawnPluc.inc and PawnPlus.dll in the folders, the compiler loads to infinity. Why?
I need to remove all the files to compile properly my gamemode.

**Comment by TommyB123** [comment]
Have you checked if your gamemode compiles with just PawnPlus added? If it hangs with only PawnPlus without eSelection then the problem lies there.

I'm not really sure how to reproduce or debug a problem like this, so unfortunately I'm not sure if I can be much help to you even if it's caused by only eSelection.

**Comment by Enz0B** [comment]
I compile with PawnPlus added.
